//
//  Dragon.swift
//  HowToTrainYourDragon
//
//  Created by alex on 20/8/2025.
//

import Foundation
import FirebaseFirestore

struct Dragon : Codable {
    
    @DocumentID var id: String?
    var type : String
    var species : String
    var bestAt : Attribute
    var attack : Int
    var defence: Int
    var speed : Int
    
    
//    //If I bring a dragon from the DB then it comes with its ID, so I will need to store it to keep it
//    init(id: String, type: String, species: String, bestAt: Attribute, attack: Int, defence: Int, speed: Int) {
//        self.id = id
//        self.type = type
//        self.species = species
//        self.bestAt = bestAt
//        self.attack = attack
//        self.defence = defence
//        self.speed = speed
//    }
//    
//    //initializer, it will be used whenever we want to create a new dragon, and therefore we won't know the id as it's autogenerated by firestore
//    init(type: String, species: String, bestAt: Attribute, attack: Int, defence: Int, speed: Int) {
//        self.type = type
//        self.species = species
//        self.bestAt = bestAt
//        self.attack = attack
//        self.defence = defence
//        self.speed = speed
//    }
    
    
}
